### ISSUE TITLE
Soliciting feedback

### ISSUE THREAD

**Issue by dwincort** [target/row-types#56]
To any users of row-types, I'm playing around with some breaking changes and am looking for feedback.  The changes are breaking enough that I'm planning on releasing the next version as `1.0.0.0` so anyone with any limits on forward-compatibility won't have a big problem, but I'd still value users' opinions.

I have four basic questions:
1. Have you ever used `Forall` or `metamorph` in your code?

2. Have you ever used the `unsafe` record or variant functions _outside of a call to `metamorph`_?

3. Have you run into issues where GHC seemed really stupid about constraints (where you needed to add a seemingly obvious constraint like `Extend l t r .! l ≈ t`)?  If so, do you have any examples?

4. Do you think it's silly that `trial`, `multiTrial`, and `split` (all of which return an Either) all put the "successful" result in `Left` and the failure in `Right`?

**Comment by nomeata** [comment]
> Have you ever used `Forall` or `metamorph` in your code?

Using `Forall` in 
https://github.com/nomeata/haskell-candid/blob/1030508cc1ae691c29a3eea227f5980fdf25c8ce/test.hs#L383-L387
and
https://github.com/nomeata/haskell-candid/blob/3d42d98ee4002395f6f88ef0769f195572c2cbf8/src/Codec/Candid/Service.hs#L45

I failed to use `metamorph`

> Have you ever used the unsafe record or variant functions outside of a call to metamorph?

Yes, here:
https://github.com/nomeata/haskell-candid/blob/1030508cc1ae691c29a3eea227f5980fdf25c8ce/src/Codec/Candid/Class.hs#L298-L326

Maybe `metamorph` might work here, I could not figure out how.

> Have you run into issues where GHC seemed really stupid about constraints

No.

> Do you think it's silly that trial, multiTrial, and split (all of which return an Either) all put the "successful" result in Left and the failure in Right?

I did not notice, as I don't use them (`switch` always seemd easier and more natural). But sounds confusing.

**Comment by woehr** [comment]
Context: I use row-types in my open-adt library, which uses row-type variants for defining data types that can be manipulated to add or remove constructors. Put another way, constructors can be shared among different data types.

> 1. Have you ever used `Forall` or `metamorph` in your code?

Yes, the main use of metamorph (metamorph' actually) is here https://github.com/woehr/open-adt/blob/e340bda1444dafd0a7621c58559dfa35bfd071eb/open-adt/lib/Data/OpenADT/VarF.hs#L82
I use Forall in many places because all "constructors" of the variants must be similarily constrained.

> 2. Have you ever used the `unsafe` record or variant functions _outside of a call to `metamorph`_?

No

> 3. Have you run into issues where GHC seemed really stupid about constraints (where you needed to add a seemingly obvious constraint like `Extend l t r .! l ≈ t`)?  If so, do you have any examples?

Yes. I have a function in open-adt (below) that I recall needing a lot of constraints in (I think I figured out which constraints I needed to get the best type-checking result through trial and error).

```
-- | Given a record of functions, use those functions to remove the
-- corresponding rows from the input. Type errors will ensue if the record
-- contains fields of the output variant.
--
-- @since 1.0
reduceVarF
  :: forall r s t x r' s' t'
   . ( t ≈ r .\\ s
     , r' ~ ApplyRow x r
     , s' ~ ApplyRow x s
     , s' ≈ r' .\\ t'
     , t' ≈ r' .\\ s'
     , Disjoint s' t'
     , Switch t' (RowFromTo t' (VarF s x)) (VarF s x)
     )
  => Rec (RowFromTo t' (VarF s x))
  -> VarF r x
  -> VarF s x
reduceVarF f (VarF v) = case multiTrial @t' @r' v of
  Left  x -> caseon f x
  Right x -> VarF x
```

> 4. Do you think it's silly that `trial`, `multiTrial`, and `split` (all of which return an Either) all put the "successful" result in `Left` and the failure in `Right`?

I never noticed or thought about it (and I have used these functions).
