### ISSUE TITLE
Segmentation fault after upgrading to row-types-1.0

### ISSUE THREAD

**Issue by nomeata** [target/row-types#74]
Quite late to the party, but it is about time I upgrade to row-types-1.0

I tried to do it, including some cargo-culting around `metamorph`, but now the test suite segfaults…

To reproduce, run `cabal run test` in this commit
https://github.com/nomeata/haskell-candid/commit/aeb1bce5833dbcc38992b3d22cd7d0a6cbd5a742 (part of branch `row-type-1.0`).

Did I do something stupid when changing metamorph? Or am I somewhere else relying on internals of row-types that have changed?

Probably the issue isn’t with your code, but thanks for your help nevertheless.

**Comment by dwincort** [comment]
> Probably the issue isn’t with your code, but thanks for your help nevertheless.

I appreciate your confidence in me, but this is entirely my fault, and I'm sorry you ran into it.  The fix is actually up on github, but I've been lazy about releasing to hackage.  I guess this is the forcing function I needed.

I'll have a new version on hackage very soon (see https://github.com/target/row-types/pull/76), and it should fix your problem.

**Comment by nomeata** [comment]
Well, at least it means your code is properly execised :-D

**Comment by dwincort** [comment]
Okay.  [row-types-1.0.1.0 is now on hackage](https://hackage.haskell.org/package/row-types-1.0.1.0).  I'd be happy to help you transition remaining bits of code to row-types-1.0 or debug any other problems you might be having.

**Comment by nomeata** [comment]
I think the commit linked above was all needed to make it compile – and surely that is all I need, right? :-)
